### ISSUE TITLE
netmask.c: 2 * pointless tests ?

### ISSUE THREAD

**Issue by dcb314** [tlby/netmask#2]
netmask.c:310]: (style) Checking if unsigned variable 'v' is less than zero.
netmask.c:313]: (style) Checking if unsigned variable 'v' is less than zero.

Source code is

```
      if(v < 0 || v > 32) return 0;
```

and

```
     if(v < 0 || v > 128) return 0;
```

**Comment by tlby** [comment]
thanks!
