### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by mosin** [tlby/netmask#7]
Great tool, super useful.

Any chance ipv6 support would be added?

**Comment by tlby** [comment]
This needs to be documented better, but you're in luck if you have v2.4.0 or later
https://github.com/tlby/netmask/blob/29a9c239bd1008363f5b34ffd6c2cef906f3660c/ChangeLog#L25

**Comment by mosin** [comment]
Thanks, could you please give me an example? I can't seem to get it to work.
$ netmask ::1-fe80::1
netmask: parse error "::1-fe80::1": Invalid argument
$ netmask -d -r 100::/64 
          100::-100::ffff:ffff:ffff:ffff (18446744073709551616)
But if I try to do the reverse:
netmask -c 100::-100::ffff:ffff:ffff:ffff
netmask: parse error "100::-100::ffff:ffff:ffff:ffff": Invalid argument

**Comment by tlby** [comment]
The tool's output and accepted inputs are not entirely inline which is unfortunate.  Anyhow, I think `,` rather than `-` will be interpreted as a range from one address to another.  For example, it will accept `::1,fe80::1` and `100::,100::ffff:ffff:ffff:ffff`
